DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS bands CASCADE;
DROP TABLE IF EXISTS instruments CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS spots CASCADE;
DROP TABLE IF EXISTS user_instrument CASCADE;
DROP TABLE IF EXISTS user_genre CASCADE;
DROP TABLE IF EXISTS band_genre CASCADE;
DROP TABLE IF EXISTS spot_applications CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  profile_image VARCHAR(255)
);

CREATE TABLE instruments (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  instrument_image VARCHAR(255)
);

CREATE TABLE genres (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE bands (
  id SERIAL PRIMARY KEY NOT NULL,
  leader_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  featured BOOLEAN DEFAULT FALSE,
  band_image VARCHAR(255)
);

CREATE TABLE spots (
  id SERIAL PRIMARY KEY NOT NULL,
  band_id INTEGER REFERENCES bands(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  instrument_id INTEGER REFERENCES instruments(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE spot_applications (
  id SERIAL PRIMARY KEY NOT NULL,
  spot_id INTEGER REFERENCES spots(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  message TEXT,
  accepted_status BOOLEAN DEFAULT NULL
); 


CREATE TABLE user_instrument (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  instrument_id INTEGER REFERENCES instruments(id) ON DELETE CASCADE
);

CREATE TABLE user_genre (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE
);

CREATE TABLE band_genre (
  band_id INTEGER REFERENCES bands(id) ON DELETE CASCADE,
  genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE
);